config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    get 'download_urls'
    get 'download_eids'
  end
  get 'elements/:project_name/:gid/:is_random',
    controller: :elements, action: :show, as: :element

end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :project
  validates :gid, presence: true, format: { with: /\A[a-zA-Z0-9_\-]+\Z/ }
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :elements
  attr_accessor :element_file

  validates :name, presence: true, format: { with: /\A[a-zA-Z0-9_\-]+\Z/ },
    uniqueness: true
  validates :font_size, numericality: { greater_than: 0 }
  validates :random_num, numericality: { greater_than: 0 }
  validates :max_width, numericality: { greater_than: 0 }
  validates :element_file, presence: true, on: :create
  validate :element_file_validation, on: :create

  def element_file_validation
    return if element_file.nil?
    lineno = 0
    CSV.foreach(element_file.tempfile.path, col_sep: "\t") do |row|
      lineno += 1
      next if row.size == 0
      if row.size != 3
        errors.add(:element_file, "Line #{lineno}: too many/few #{row.size} fileds")
      end
      gid = row[0]
      eid = row[1]
      body = row[2]
      element = elements.build(gid: gid, eid: eid, body: body)
      unless element.valid?
        element.errors.each do |key, msg|
          errors.add(:element_file, "Line #{lineno}: #{key} #{msg}")
        end
      end
    end
  end

  def random_elements(gid, seed)
    gid_elements = elements.where(gid: gid).order(:id).to_a
    unless seed.nil?
      random = Random.new(seed)
      gid_elements.shuffle!(random: random)
    end
    return gid_elements
  end

  def get_max_element_num_per_gid
    elements.group(:gid).count.values.max
  end

  # Set font family and size and return Draw
  def get_draw
    draw = Magick::Draw.new
    draw.font = Settings.font.path
    draw.pointsize = font_size
    return draw
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_project, :get_seed, :set_elements, :set_draw, :set_img

  def show
    height = @project.font_size
    x = @project.offset_x
    seed_text = @seed.nil? ? " " : @seed.to_s
    @draw.annotate(@img, 0, 0, x, height + @project.offset_y, seed_text)
    @elements.each_with_index do |elem, idx|
      y = height*(idx+2) + @project.offset_y
      @draw.annotate(@img, 0, 0, x, y, elem.body)
    end
    send_data(@img.to_blob, disposition: "inline", type: "image/png")
  end

  private
    def set_project
      @project = Project.find_by(name: params[:project_name])
    end

    def get_seed
      cookies[:seed] ||= rand(@project.random_num)
      @seed = cookies[:seed].to_i
    end

    def set_elements
      is_random = params[:is_random] != "0"
      @seed = is_random ? @seed : nil
      @elements = @project.random_elements(params[:gid], @seed)
    end

    def set_draw
      @draw = @project.get_draw
    end

    def set_img
      @img = Magick::Image.new(@project.max_width, @project.font_size*(@elements.size + 1))
      @img.format = 'png'
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /projects/1/edit
  # GET /projects/1/edit.json
  def edit
  end

  # PATCH /projects
  # PATCH /projects.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Downloads
  def download_urls
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.html { redirect_to :action => 'download_urls', :format => 'tsv' }
      format.tsv { render :content_type => 'text/tsv' }
    end
  end

  def download_eids
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.html { redirect_to :action => 'download_eids', :format => 'tsv' }
      format.tsv { render :content_type => 'text/tsv' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :font_size, :random_num, 
        :max_width, :offset_x, :offset_y, :element_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/_flash.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == "notice" ? "success" : "danger"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = msg

app/views/application/_header.html.haml
.navbar.navbar-default{:role => "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'Top', "", class: "navbar-brand"
  .navbar-collapse.collapse.navbar-responsive-collapse
    %ul.nav.navbar-nav
      %li
        = link_to 'Projects', projects_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Randomage"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body

    %header
      = render partial: 'application/header'
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      %footer
        = render partial: 'application/footer'

app/views/projects/_form.html.haml
= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :font_size
  = f.input :random_num
  = f.input :max_width
  = f.input :offset_x
  = f.input :offset_y
  - if @project.new_record?
    = f.input :element_file, as: :file
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn btn-default'

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/index.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.id
        %td= link_to project.name, project_path(project), class: 'btn btn-default btn-block'
        %td=l project.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(project), :class => 'btn btn-xs btn-default'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_project_path, :class => 'btn btn-primary'

app/views/projects/new.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/show.html.haml
- model_class = Project
.page-header
  %h1=@project.name

%p
  =link_to "Download URLs", project_download_urls_path(@project.id, format: :tsv),
    class: "btn btn-primary"
  =link_to "Download EIDs", project_download_eids_path(@project.id, format: :tsv),
    class: "btn btn-primary"
%p
  = link_to t('.back', :default => t("helpers.links.back")), projects_path, :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(@project), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(@project), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

%table.table.table-condensed
  %thead
    %tr
      %th Attribute
      %th Value
  %tbody
    %tr
      %td Font size
      %td=@project.font_size
    %tr
      %td Random num
      %td=@project.random_num
    %tr
      %td Max width
      %td=@project.max_width
    %tr
      %td Offset X
      %td=@project.offset_x
    %tr
      %td Offset Y
      %td=@project.offset_y
    %tr
      %td Max element num per GID
      %td=@project.get_max_element_num_per_gid

%table.table.table-condensed
  %thead
    %tr
      %th GID
      %th EID
      %th Body
      %th Preview
  %tbody
    - @project.elements.group_by(&:gid).each do |gid, elems|
      - elems.each_with_index do |elem, idx|
        %tr
          %td=elem.gid
          %td=elem.eid
          %td=elem.body
          %th
            %div{style: {height: "#{@project.font_size}px", width: "#{@project.max_width}px",
              background: "url('#{element_path(@project.name, elem.gid, 0)}') no-repeat 0px -#{(idx+1)*@project.font_size}px"}.map {|k, v| "#{k}: #{v};"}.join(" ")}